runtime: python27
api_version: 1
threadsafe: true
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic  # default value
  min_pending_latency: 60ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50

libraries:
- name: pytz
  version: "2016.4"
- name: numpy
  version: "1.6.1"
- name: jinja2
  version: "latest"

inbound_services:
- mail
- warmup

handlers:
- url: /static
  static_dir: static

- url: /_ah/mail/.+
  script: handle_incoming_email.app
  login: admin

- url: /admin/.*
  script: main.app
  login: admin

- url: /_ah/warmup
  script: main.app
  login: admin

- url: /.*
  script: main.app
  secure: always
