runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: pytz
  version: "2016.4"
- name: numpy
  version: "1.6.1"
- name: jinja2
  version: "latest"

handlers:

- url: /static
  static_dir: static

- url: /.*
  script: main.app
